# Site settings
title:       Lifeblog
email:       dtu.amit@gmail.com
author:      Amit Kumar
description: "Lifeblog by Programmer"
baseurl:     "/lifeblog"
url:         "http://iamit.in/lifeblog"

# Google analytics
google_analytics: true

# Optional features
animated:           true
show_related_posts: true
show_post_footers:  true

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: amitlifeblog
comments: true


# Social icons
show_social_icons: true
github_username: aktech
stackoverflow_id:
twitter_username: iaktech
google_plus_id:
linkedin_username:
angellist_username:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: true
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: true
share_linkedin: true
share_digg: true
share_tumblr: true
share_reddit: true
share_stumbleupon: true
share_hackernews: true

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     6
sass:
  compressed: true
